blank_issues_enabled: true
contact_links:
  - name: Discussions - Translations
    url: https://github.com/orgs/BeaniumMC/discussions/categories/translations
    about: Please ask and answer questions here.
