name: ✏️ Report Translation or Spelling Error
description: Report a typo, translation error, or incorrect language usage
title: '[Translation Error] '
labels: ['translation']
body:
  - type: input
    id: project
    attributes:
      label: Project
      description: Which project has an error?
      placeholder: e.g. Server
    validations:
      required: true

  - type: input
    id: language
    attributes:
      label: Language
      description: Which language is affected?
      placeholder: e.g. French
    validations:
      required: true

  - type: input
    id: file
    attributes:
      label: File or Key Path
      description: Where is the error? Provide the filename or translation key.
      placeholder: e.g. core.json → "welcome_message"
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Correction
      description: What should it say instead?
      placeholder: e.g. "Bienvenue"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Context (optional)
      description: Include any context that might help us understand the issue.
      placeholder: e.g. "This is the first thing users see on the homepage."
